HospitalManagement/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:edit, :update]
  resources :doctor_infos
  resources :appointments do 
    member do
      put :update_status
    end
    collection do
      get :get_time_slots
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "appointments#index"
end

HospitalManagement/app/models/appointment.rb
class Appointment < ApplicationRecord
  # associations
  belongs_to :user
  belongs_to :doctor, class_name: "User"

  # enums
  enum :status, [ :pending, :accepted, :rejected ]

  # validations
  validates :appointment_date, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :appointment_date, comparison: { greater_than_or_equal_to: Date.today, less_than_or_equal_to: Date.current + 7.days, message: I18n.t('appointment.seven_days_prior_only', upto_date: (Date.current + 7.days).strftime("%d/%m/%Y")) }, allow_blank: false, if: :appointment_date
  validates :start_at, comparison: { greater_than: DateTime.now }, allow_blank: false, if: :start_at
  validates :end_at, comparison: { greater_than: :start_at ,message: I18n.t('appointment.end_time_smaller') }, allow_blank: false, if: :end_at
  validate :doctor_availability, if: :new_record?
  validate :user_has_appointment_in_selecting_slot, if: :new_record?
  validate :slot_must_be_one_hour_only, if: :new_record?
  validate :timing_must_be_as_doctor_availability, if: :new_record?

  # callbacks
  before_validation :convert_timing_for_selected_date

  def doctor_availability
    doctor_appointments = Appointment.where(doctor_id: self.doctor_id, appointment_date: self.appointment_date)
    errors.add(:base, I18n.t('appointment.doctor_unavailable')) if doctor_appointments.where('start_at < ? AND end_at > ?', self.end_at, self.start_at).present?
  end

  def user_has_appointment_in_selecting_slot
    user_appointments = Appointment.where(user_id: self.user_id, appointment_date: self.appointment_date)
    errors.add(:base, I18n.t('appointment.user_unavailable')) if user_appointments.where('start_at < ? AND end_at > ?', self.end_at, self.start_at).present?
  end

  def timing_must_be_as_doctor_availability
    doctor = User.with_role(:doctor).find_by(id: self.doctor_id)
    doctor_timing = doctor&.doctor_info&.doctor_timings.find_by(weekday: self.appointment_date&.wday)
    if doctor_timing.present? && self.start_at.present? && self.end_at.present?
      errors.add(:base, "Invalid slot choosen") unless doctor_timing.selected_slot_valid?(self.appointment_date, self.start_at, self.end_at)
    else
      errors.add(:base, I18n.t('appointment.doctor_not_available'))
    end
  end

  def slot_must_be_one_hour_only
    if self.start_at.present? && self.end_at.present?
      errors.add(:base, I18n.t('appointment.slot_must_be_hour')) unless self.end_at == self.start_at + 1.hour
    else
      errors.add(:base, "Please select valid Time Slot")
    end
  end

  def convert_timing_for_selected_date
    self.start_at = DateTime.parse("#{self.appointment_date} #{self.start_at.strftime('%H:%M')} +0530")
    self.end_at = DateTime.parse("#{self.appointment_date} #{self.end_at.strftime('%H:%M')} +0530")
  end
end

HospitalManagement/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, only: [:update_status]

  def index
    if params[:history]
      @appointments = current_user.appointments.where('appointment_date < ?', Date.today).order(appointment_date: :desc)
    else
      @appointments = current_user.appointments.where('appointment_date >= ?', Date.today).order(appointment_date: :asc)
    end
    authorize @appointments
  end

  def new
    @appointment = current_user.appointments.build
    authorize @appointment
  end

  def create
    @appointment = current_user.appointments.build(appointment_params)
    authorize @appointment
    if @appointment.save
      redirect_to root_path, notice: "Appointment Created Successfully"
    else
      flash[:alert] = @appointment.errors.full_messages.join(', ')
      render :new
    end
  end

  def get_time_slots
    doctor = User.with_role(:doctor).find_by(id: params[:doctor_id])
    time_slots = doctor.doctor_info.available_time_slots(params[:appointment_date]) if doctor&.doctor_info.present?
    respond_to do |format|
      format.js { render json: { time_slots: time_slots } }
    end
  end

  def update_status
    authorize @appointment
    @appointment.update(status: params[:status].to_i)
    redirect_to appointments_path
  end

  private

  def find_appointment
    @appointment = Appointment.find_by_id(params[:id])
  end

  def appointment_params
    params.permit(:id, :user_id, :doctor_id, :appointment_date, :start_at, :end_at, :status)
  end
end

HospitalManagement/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

HospitalManagement/app/views/appointments/index.html.erb
<br/>
<h2><%= params[:history] == 'true' ? 'History Appointments' : 'Upcoming Appointments' %></h2>
<% if patient_signed_in? %>
  <br/>
  <%= link_to 'Book Appointment', new_appointment_path, class: 'btn border-primary' %>
<% end %>
<br/>
<br/>
<table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th>No</th>
      <th>Appointment Date</th>
      <% if patient_signed_in? %>
        <th>Doctor Name</th>
      <% else %>
        <th>Patient Name</th>
      <% end %>
      <th>Start At</th>
      <th>End At</th>
      <% if doctor_signed_in? && params[:history] != 'true' %>
        <th>Doctor Status</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% if @appointments.present? %>
      <% @appointments.each_with_index do |appointment, index| %>
        <tr>
          <td><%= index + 1 %>
          <td><%= appointment.appointment_date.strftime("%d/%m/%Y") %></td>
          <% if patient_signed_in? %>
            <td><%= appointment.doctor.full_name %></td>
          <% else %>
            <td><%= appointment.user.full_name %></td>
          <% end %>
          <td><%= appointment.start_at.strftime("%H:%M") %></td>
          <td><%= appointment.end_at.strftime("%H:%M") %></td>
          <% if doctor_signed_in? && params[:history] != 'true' %>
            <td>
              <% if appointment.status == Appointment.statuses.key(0) %>
                <%= link_to 'Accept', update_status_appointment_path(id: appointment.id, status:  Appointment.statuses[:accepted]), method: :put, class: 'btn btn-success btn-sm' %>
                <%= link_to 'Reject', update_status_appointment_path(id: appointment.id, status:  Appointment.statuses[:rejected]), method: :put, class: 'btn btn-danger btn-sm' %>
              <% else %>
                <%= appointment.status.titleize %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

HospitalManagement/app/views/appointments/new.html.erb
<h2> Book Appointment </h2>
<br/><br/>
<%= form_with url: appointments_path, method: :post do |f| %>
  <div class="mb-3 row">
    <%= f.label :doctor_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.select :doctor_id, User.with_role(:doctor).pluck(:full_name, :id), {}, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :appointment_date, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.date_field :appointment_date, min: Date.today, max: Date.today + 7 , class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :slot, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.select :slot, ["Time Slots"], {}, class: "form-control" %>
    </div>
  </div>

  <%= f.hidden_field :start_at, value: '' %>
  <%= f.hidden_field :end_at, value: '' %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<script type="module">
  $(document).ready(function(){
    $("#doctor_id, #appointment_date").change(function() {
      if($('#doctor_id').val() != '' && $('#appointment_date').val() != ''){
        $.ajax({
          url: '/appointments/get_time_slots',
          type: 'GET',
          dataType: 'script',
          data: {
            doctor_id: $('#doctor_id').val(),
            appointment_date: $('#appointment_date').val()
          },
          success: function(data){
            var response = JSON.parse(data)
            if(response["time_slots"] == null ){
              $('#slot').empty().append("<option value=''>No Slots available</option>")
            }else{
              $('#slot').empty().append(response["time_slots"].flatMap((x) => "<option value='" + x + "'>" + x + "</option>"))
              var time_slot = $.map(response["time_slots"][0].split("-"), $.trim);
              $('#start_at').val(time_slot[0]);
              $('#end_at').val(time_slot[1]);
            }
          },
        });
      }
    });

    $('#slot').change(function() {
      if($(this).val() != ''){
        var time_slot = $.map($('#slot').val().split("-"), $.trim);
        $('#start_at').val(time_slot[0]);
        $('#end_at').val(time_slot[1]);
      } 
    });
  });
</script>