HospitalManagement/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:edit, :update]
  resources :doctor_infos
  resources :appointments do 
    member do
      put :update_status
    end
    collection do
      get :get_time_slots
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "appointments#index"
end

HospitalManagement/app/views/layouts/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: flash_classes(type) %>
<% end %>

HospitalManagement/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">HMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'History Appointments', appointments_path(history: true), class: "nav-link" %>
        </li>
        <% if doctor_signed_in? %>
          <li class="nav-item">
            <% if current_user.doctor_info&.persisted? %>
              <%= link_to 'Profile', edit_doctor_info_path(current_user.doctor_info), class: 'nav-link'  %>
            <% else %>
              <%= link_to 'Profile', new_doctor_info_path, class: 'nav-link' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <b><%= current_user.full_name %></b>&nbsp
    <%= button_to 'Logout', destroy_user_session_path, method: :delete, 'data-turbo': false, class: 'btn btn-danger' %>
  </div>
</nav>

HospitalManagement/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless user_signed_in? %>
      <%= yield %>
    <% end %>
    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_message' %>
      <div class="container">  
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>